[technote]
id = "RTN-073"
series_id = "RTN"
canonical_url = "https://rtn-073.lsst.io"
github_url = "https://github.com/lsst/rtn-073"
github_default_branch = "main"
date_created = 2024-01-30T15:12:15Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Richard"
name.family = "Dubois"
internal_id = "duboisr"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
